### ISSUE TITLE
Trivial password set by default

### ISSUE THREAD

**Issue by phoe** [fsmunoz/cl-watson-iot-example#1]
https://github.com/fsmunoz/cl-watson-iot-example/blob/master/cl-watson-iot.lisp#L24

Please make sure that, if no password is set, the system will prompt the user to set a proper password. You can achieve it by, for example, not binding any value to `*PASSWORD*` despite proclaiming it as a global variable.

```lisp
(defvar *password*)
```

**Comment by fsmunoz** [comment]
Hello,

Thank you for your comment; this example code is a companion to this article: https://developer.ibm.com/recipes/tutorials/watson-iot-with-common-lisp/ and that's why have left defaults values in (they are references in the article as well); that said it is likely better to change both *password* and *org-id* and add instructions to change them. I will do that soon.
